#!/usr/bin/python3
#+
# This script generates integer bitmask repesentations of the printer
# characters.
#
# Written by Lawrence D'Oliveiro <ldo@geek-central.gen.nz>.
#-

import sys

bits = \
    {
        0 :
            (
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
            ),
        1 :
            (
                " XXX ",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                " XXX ",
            ),
        2 :
            (
                "  X  ",
                " XX  ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
                " XXX ",
            ),
        3 :
            (
                " XXX ",
                "X   X",
                "    X",
                "  XX ",
                " X   ",
                "X    ",
                "XXXXX",
            ),
        4 :
            (
                " XXX ",
                "X   X",
                "    X",
                "  XX ",
                "    X",
                "X   X",
                " XXX ",
            ),
        5 :
            (
                "   X ",
                "  XX ",
                " X X ",
                "X  X ",
                "XXXXX",
                "   X ",
                "   X ",
            ),
        6 :
            (
                "XXXXX",
                "X    ",
                "XXXX ",
                "    X",
                "    X",
                "X   X",
                " XXX ",
            ),
        7 :
            (
                "  XX ",
                " X   ",
                "X    ",
                "XXXX ",
                "X   X",
                "X   X",
                " XXX ",
            ),
        10 :
            (
                "XXXXX",
                "    X",
                "   X ",
                "  X  ",
                " X   ",
                " X   ",
                " X   ",
            ),
        11 :
            (
                " XXX ",
                "X   X",
                "X   X",
                " XXX ",
                "X   X",
                "X   X",
                " XXX ",
            ),
        12 :
            (
                " XXX ",
                "X   X",
                "X   X",
                " XXXX",
                "    X",
                "   X ",
                " XX  ",
            ),
        13 :
            (
                " XXX ",
                "X   X",
                "X   X",
                "XXXXX",
                "X   x",
                "X   X",
                "X   X",
            ),
        14 :
            (
                "XXXX ",
                "X   X",
                "X   X",
                "XXXX ",
                "X   X",
                "X   X",
                "XxXX ",
            ),
        15 :
            (
                " XXX ",
                "X   X",
                "X    ",
                "X    ",
                "X    ",
                "X   X",
                " XXX ",
            ),
        16 :
            (
                "XXXX ",
                " X  X",
                " X  X",
                " X  X",
                " X  X",
                " X  X",
                "XXXX ",
            ),
        17 :
            (
                "XXXXX",
                "X    ",
                "X    ",
                "XXXX ",
                "X    ",
                "X    ",
                "XXXXX",
            ),
        20 :
            (
                "     ",
                "     ",
                "     ",
                "XXXXX",
                "     ",
                "     ",
                "     ",
            ),
        21 :
            (
                "XXXXX",
                "X    ",
                "X    ",
                "XXXX ",
                "X    ",
                "X    ",
                "X    ",
            ),
        22 :
            (
                " XXX ",
                "X   X",
                "X    ",
                "X    ",
                "X  XX",
                "X   X",
                " XXXX",
            ),
        23 :
            (
                "X   X",
                "X   X",
                "X   X",
                "XXXXX",
                "X   X",
                "X   X",
                "X   X",
            ),
        24 :
            (
                " XXX ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
                " XXX ",
            ),
        25 :
            (
                "    X",
                "    X",
                "    X",
                "    X",
                "    X",
                "X   X",
                " XXX ",
            ),
        26 :
            (
                "X   X",
                "X  X ",
                "X X  ",
                "XX   ",
                "X X  ",
                "X  X ",
                "X   X",
            ),
        27 :
            (
                "X    ",
                "X    ",
                "X    ",
                "X    ",
                "X    ",
                "X    ",
                "XXXXX",
            ),
        30 :
            (
                "X   X",
                "XX XX",
                "X X X",
                "X X X",
                "X   X",
                "X   X",
                "X   X",
            ),
        31 :
            (
                "X   X",
                "X   X",
                "XX  X",
                "X X X",
                "X  XX",
                "X   X",
                "X   X",
            ),
        32 :
            (
                "XXXXX",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                "XXXXX",
            ),
        33 :
            (
                "XXXX ",
                "X   X",
                "X   X",
                "XXXX ",
                "X    ",
                "X    ",
                "X    ",
            ),
        34 :
            (
                " XXX ",
                "X   X",
                "X   X",
                "X   X",
                "X X X",
                "X  XX",
                " XXXX",
            ),
        35 :
            (
                "XXXX ",
                "X   X",
                "X   X",
                "XXXX ",
                "X X  ",
                "X  X ",
                "X   X",
            ),
        36 :
            (
                " XXX ",
                "X   X",
                "X    ",
                " XXX ",
                "    X",
                "X   X",
                " XXX ",
            ),
        37 :
            (
                "XXXXX",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
            ),
        40 :
            (
                "     ",
                "     ",
                "     ",
                "     ",
                "     ",
                " XX  ",
                " XX  ",
            ),
        41 :
            (
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                "X   X",
                " XXX ",
            ),
        42 :
            (
                "X   X",
                "X   X",
                "X   X",
                " X X ",
                " X X ",
                "  X  ",
                "  X  ",
            ),
        43 :
            (
                "X   X",
                "X   X",
                "X   X",
                "X X X",
                "X X X",
                "X X X",
                " X X ",
            ),
        44 :
            (
                "X   X",
                "X   X",
                " X X ",
                "  X  ",
                " X X ",
                "X   X",
                "X   X",
            ),
        45 :
            (
                "X   X",
                "X   X",
                " X X ",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
            ),
        46 :
            (
                "XXXXX",
                "    X",
                "   X ",
                "  X  ",
                " X   ",
                "X    ",
                "XXXXX",
            ),
        47 :
            (
                "     ",
                "  X  ",
                "  X  ",
                "XXXXX",
                "  X  ",
                "  X  ",
                "     ",
            ),
        50 :
            (
                "     ",
                "X   X",
                " X X ",
                "  X  ",
                " X X ",
                "X   X",
                "     ",
            ),
        51 :
            (
                "     ",
                " X X ",
                "  X  ",
                "XXXXX",
                "  X  ",
                " X X ",
                "     ",
            ),
        52 :
            (
                " XXXX",
                " X   ",
                " X   ",
                " X   ",
                " X   ",
                "XX   ",
                " X   ",
            ),
        53 :
            (
                "     ",
                "    X",
                " XXX ",
                "XX X ",
                " X X ",
                " X X ",
                " X X ",
            ),
        54 :
            (
                "     ",
                "     ",
                " XXX ",
                "X   X",
                "XXXXX",
                "X    ",
                " XXX ",
            ),
        55 :
            (
                "    X",
                "   X ",
                "  X  ",
                "  X  ",
                "  X  ",
                "   X ",
                "    X",
            ),
        56 :
            (
                "X    ",
                " X   ",
                "  X  ",
                "  X  ",
                "  X  ",
                " X   ",
                "X    ",
            ),
        57 :
            (
                "     ",
                "     ",
                "     ",
                "XX   ",
                "XX   ",
                " X   ",
                "X    ",
            ),
        60 :
            (
                "  X  ",
                " XXX ",
                "X X X",
                "  X  ",
                "  X  ",
                "  X  ",
                "  X  ",
            ),
        61 :
            (
                "XX   ",
                "XX  X",
                "   X ",
                "  X  ",
                " X   ",
                "X  XX",
                "   XX",
            ),
        62 :
            (
                "  X  ",
                "  XX ",
                "  X  ",
                "     ",
                "  X  ",
                " XX  ",
                "  X  ",
            ),
        63 :
            (
                "     ",
                "    X",
                "   X ",
                "  X  ",
                " X   ",
                "X    ",
                "     ",
            ),
        64 :
            (
                "     ",
                "     ",
                "XXXXX",
                "     ",
                "XXXXX",
                "     ",
                "     ",
            ),
        65 :
            (
                "  XX ",
                "  XX ",
                "  XX ",
                "     ",
                "     ",
                "     ",
                "     ",
            ),
        66 :
            (
                "X   X",
                " X X ",
                "  X  ",
                " X X ",
                "X   X",
                "     ",
                "     ",
            ),
        67 :
            (
                "XXXXX",
                "     ",
                "X   X",
                " X X ",
                "  X  ",
                " X X ",
                "X   X",
            ),
        70 :
            (
                "XXX  ",
                "   X ",
                " XX  ",
                "X    ",
                "XXXX ",
                "     ",
                "     ",
            ),
        71 :
            (
                " XXX ",
                "X   X",
                "X   X",
                "   X ",
                "  X  ",
                "     ",
                "  X  ",
            ),
        72 :
            (
                "     ",
                "  X  ",
                "     ",
                "XXXXX",
                "     ",
                "  X  ",
                "     ",
            ),
        73 :
            (
                "  X  ",
                " X X ",
                " X X ",
                " X X ",
                "  X  ",
                "     ",
                "  X  ",
            ),
        74 :
            (
                "XXXXX",
                " X X ",
                " X X ",
                " X X ",
                " X X ",
                " X X ",
                "XXXXX",
            ),
        75 :
            (
                "     ",
                "     ",
                "     ",
                "     ",
                "  X  ",
                " X X ",
                "X X X",
            ),
        76 :
            (
                "XXXXX",
                " X X ",
                " X X ",
                " X X ",
                " X X ",
                " X X ",
                " X X ",
            ),
        77 :
            (
                "XXXXX",
                " X   ",
                "  X  ",
                "   X ",
                "  X  ",
                " X   ",
                "XXXXX",
            ),
    }

sys.stdout.write("{\n")
for row in range(0, 8) :
    for col in range(0, 8) :
        glyph = bits[row * 10 + col]
        sys.stdout.write("    {")
        for line in range(0, 7) :
            if line != 0 :
                sys.stdout.write(", ")
            #end if
            mask = 1
            val = 0
            for bit in glyph[line] :
                if bit != " " :
                    val |= mask
                #end if
                mask <<= 1
            #end for
            sys.stdout.write("0x%02x" % val)
        #end for
        sys.stdout.write("}, /*%02d*/\n" % (row * 10 + col))
    #end for
#end for
sys.stdout.write("}\n")
